# Generated by Django 3.0 on 2020-07-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogRecordsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.CharField(blank=True, default='0', max_length=80, null=True, verbose_name='Actor ID')),
                ('log_detail', models.TextField(blank=True, null=True, verbose_name='Log Detail')),
                ('targeted_instance_id', models.CharField(blank=True, default='0', max_length=80, null=True, verbose_name='Targeted Instance ID')),
                ('event_path', models.TextField(blank=True, null=True, verbose_name='Event Path')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Log Record',
                'verbose_name_plural': 'Log Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
