# Generated by Django 3.0 on 2020-07-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecordsmodel',
            name='event_path',
            field=models.TextField(blank=True, default='n/a', null=True, verbose_name='Event Path'),
        ),
        migrations.AlterField(
            model_name='logrecordsmodel',
            name='log_detail',
            field=models.TextField(blank=True, default='n/a', null=True, verbose_name='Log Detail'),
        ),
    ]
