# Generated by Django 3.0 on 2020-07-26 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('event_logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecordsmodel',
            name='event_path',
            field=models.TextField(default='n/a', verbose_name='Event Path'),
        ),
        migrations.AlterField(
            model_name='logrecordsmodel',
            name='user_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_user', to='contenttypes.ContentType', verbose_name='Log User Content Type'),
        ),
    ]
