# Generated by Django 3.0 on 2020-07-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_logger', '0002_auto_20200726_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecordsmodel',
            name='log_detail',
            field=models.TextField(default='no specified operation', verbose_name='Log Detail'),
        ),
    ]
