# Generated by Django 3.0 on 2020-07-27 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('event_logger', '0003_auto_20200726_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecordsmodel',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_target_content_type', to='contenttypes.ContentType', verbose_name='Log Target Content Type'),
        ),
        migrations.AlterField(
            model_name='logrecordsmodel',
            name='user_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_user_content_type', to='contenttypes.ContentType', verbose_name='Log User Content Type'),
        ),
    ]
