# Generated by Django 3.0 on 2020-07-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_logger', '0004_auto_20200727_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecordsmodel',
            name='user_object_id',
            field=models.CharField(db_index=True, default='0', max_length=255, verbose_name='Log User ID'),
        ),
    ]
