# Generated by Django 3.0 on 2020-07-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_logger', '0005_auto_20200728_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecordsmodel',
            name='target_object_id',
            field=models.CharField(db_index=True, default='0', max_length=255, verbose_name='Log Target Object ID'),
        ),
    ]
