# Generated by Django 3.0 on 2020-07-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_logger', '0006_auto_20200731_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecordsmodel',
            name='target_object_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Log Target Object ID'),
        ),
    ]
